name: Swift Package CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: swift-package-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      # actions/checkout@v4
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          persist-credentials: false

      - name: Show Swift Version
        run: swift --version

      - name: Build Package
        run: swift build

      - name: Test Package
        run: swift test
